{{- if and (not .Values.auth.existingSecretName) .Values.auth.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cert-manager-proxy.authSecretName" . }}
  labels:
    {{- include "cert-manager-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.existingSecretKey }}: {{ .Values.auth.token | quote }}
{{- end }}
